<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart 
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'di\\configuration' => '/lib/Configuration.php',
                'di\\configuration_builder' => '/lib/Configuration/Builder.php',
                'di\\configuration_jsonloader' => '/lib/Configuration/JsonLoader.php',
                'di\\configuration_loader' => '/lib/Configuration/Loader.php',
                'di\\container' => '/lib/Container.php',
                'di\\service_configuration' => '/lib/Service/Configuration.php',
                'di\\service_configurationinterface' => '/lib/Service/ConfigurationInterface.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd