<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart 
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'configuration' => '/lib/Configuration.php',
                'configuration_builder' => '/lib/Configuration/Builder.php',
                'configuration_jsonloader' => '/lib/Configuration/JsonLoader.php',
                'configuration_loader' => '/lib/Configuration/Loader.php',
                'container' => '/lib/Container.php',
                'dummycontainer' => '/lib/DummyContainer.php',
                'naivecontainer' => '/lib/NaiveContainer.php',
                'service_configuration' => '/lib/Service/Configuration.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd